#!/bin/bash

# Make sure we are in the script directory
ScriptDIR=$(cd `dirname $0` && pwd)
if [ $ScriptDIR != $PWD ]; then
   echo "Ce script doit être executé depuis son dossier" 1>&2
   exit
fi

#On récupère le nombre de sessions actives de Yane
C=`sudo ./yane  -l | wc -l`

#On vérifie qu'aucune session n'est déjà lancée
if [ "$C" != "0" ] ; then
  echo "Une session est déjà lancée pour la fermer executez la commande:"
  echo "   STOP"
  exit

else
  #On copie les scripts dans le dossier partagé du Docker correspondant
  cp ./scripts/Serveur_Web_Client ./files/Serveur_Web_Client/var/scripts/init
  cp ./scripts/BOX1 ./files/BOX1/etc/scripts/init
  cp ./scripts/BOX2 ./files/BOX2/etc/scripts/init
  cp ./scripts/R1 ./files/R1/etc/scripts/init
  cp ./scripts/R2 ./files/R2/etc/scripts/init
  cp ./scripts/Routeur_FAI_services ./files/Routeur_FAI_services/etc/scripts/init
  cp ./scripts/Serveur_Web ./files/Serveur_Web/var/scripts/init
  cp ./scripts/Serveur_DNS ./files/Serveur_DNS/etc/scripts/init
  cp ./scripts/Routeur_FAI_Acces ./files/Routeur_FAI_Acces/etc/scripts/init
  echo 'Chargement des VM..'
  #On lance Yane
  sudo ./yane > /dev/null
  exit
fi
