#!/bin/bash
#echo 1 > /proc/sys/net/ipv4/ip_forward 
#Set up eth0 interface
ip link set dev eth0 up
ip addr add 192.168.180.37/27 dev eth0

#Set up eth1 interface
ip link set dev eth1 up
ip addr add 11.0.0.34/27 dev eth1

ip route add default via 11.0.0.35
#ip route add 11.0.0.16/28 via 11.0.0.35
#ip route add 11.0.0.64/26 via 11.0.0.35
#ip route add 11.0.0.128/28 via 11.0.0.35


# Configurate the DHCP server
# Start the dhcp service
service isc-dhcp-server start
# Set up NAT by adding rule to iptables
iptables -t nat -A POSTROUTING -o eth1 -j MASQUERADE
# Configure default route to allow to Utilisateur_1 to communicate with FAI
## Filtrage

iptables -F
iptables -X
# Drop everything
iptables -t filter -P INPUT DROP
iptables -t filter -P OUTPUT DROP
iptables -t filter -P FORWARD DROP

# Allow ping
iptables -A INPUT -p icmp -j ACCEPT
iptables -A OUTPUT -p icmp -j ACCEPT
iptables -A FORWARD -p icmp -j ACCEPT

# Allow DHCP
iptables -A INPUT -i eth0 -p udp --dport 520 -j ACCEPT
iptables -A OUTPUT -o eth0 -p udp --dport 520 -j ACCEPT
#Allow DNS
iptables -t filter -A FORWARD -d 11.0.0.65/26 -p udp --dport 53 -j ACCEPT
iptables -t filter -A FORWARD -s 11.0.0.65/26 -p udp --dport 53 -j ACCEPT

#Allow HTTP
iptables -t filter -A FORWARD -d 11.0.0.66/26 -p tcp --dport 80 -j ACCEPT
iptables -t filter -A FORWARD -s 11.0.0.66/26 -p tcp --dport 80 -j ACCEPT

