#!/bin/bash

#Set up eth0 interface
ip link set dev eth0 up
#set private adress on eth0 
ip a a 11.0.0.130/25 dev eth0
 
#Set up eth1 interface
ip link set dev eth1 up
#set private adress on eth1
ip a a 11.0.0.17/28 dev eth1

#Static routing
#Activate the forwarding
echo 1 > /proc/sys/net/ipv4/ip_forward
#Dynamic rooting
service quagga start
