#!/bin/bash

#Set up eth0 interface
ip link set dev eth0 up
#set private adress 11.0.0.19/28 on eth0 
ip addr add 11.0.0.19/28 dev eth0

#Set up eth1 interface
ip link set dev eth1 up
#set private adress 11.0.0.67/26 on eth1
ip addr add 11.0.0.67/26  dev eth1


#Static routing
#Activate the forwarding
echo 1 >/proc/sys/net/ipv4/ip_forward

#Dynamic rooting
service quagga start

## Filtrage

iptables -F
iptables -X
# Drop everything
iptables -t filter -P INPUT DROP
iptables -t filter -P OUTPUT DROP
iptables -t filter -P FORWARD DROP

# Allow ping
iptables -A INPUT -p icmp -j ACCEPT
iptables -A OUTPUT -p icmp -j ACCEPT
iptables -A FORWARD -p icmp -j ACCEPT

# Allow DHCP
iptables -A INPUT -i eth0 -p udp --dport 520 -j ACCEPT
iptables -A OUTPUT -o eth0 -p udp --dport 520 -j ACCEPT
#Allow DNS
iptables -t filter -A FORWARD -d 11.0.0.65/26 -p udp --dport 53 -j ACCEPT
iptables -t filter -A FORWARD -s 11.0.0.65/26 -p udp --dport 53 -j ACCEPT

#Allow HTTP
iptables -t filter -A FORWARD -d 11.0.0.66/26 -p tcp --dport 80 -j ACCEPT
iptables -t filter -A FORWARD -s 11.0.0.66/26 -p tcp --dport 80 -j ACCEPT

