#!/bin/bash
# Set address on eth0
ip link set dev eth0 up
ip addr add 11.0.0.66/26 dev eth0

# Add default route via services router
ip route add default via 11.0.0.67

# Start Apache2 Server 
service apache2 start
